name: Release to Fly

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1

      - name: Package app
        run: |
          zip -r dumb-music-player.zip . \
            --exclude "*.git*" \
            --exclude "__pycache__/*" \
            --exclude "*.pyc" \
            --exclude "tests/*" \
            --exclude "*.png"

      - name: Upload release to Fly
        uses: jfrog/fly-action/upload@v1
        with:
          name: dumb-music-player
          version: ${{ github.sha }}
          files: dumb-music-player.zip
